import Header from "@/layouts/header/Header"
import type { Metadata } from "next"
import Providers from "./Providers"
import styles from "./globals.module.scss"
import "./tailwind.css"

export const metadata: Metadata = {
  title: "StudyEra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={styles.body}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
